apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
  namespace: default
spec:
  rules:
  - host: express.app.lpscogna.site
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: mongo-express
              port:
                number: 8081
