apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  labels:
    app: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Ajuste o tamanho conforme necessário
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:1.2.4
        ports:
        - containerPort: 9200
        - containerPort: 9600
        env:
        - name: discovery.type
          value: single-node
        - name: plugins.security.ssl.http.enabled
          value: "false"
        - name: plugins.security.disabled
          value: "true"
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data # Caminho para dados do OpenSearch
      volumes:
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: opensearch
