apiVersion: v1
kind: Service
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  ports:
  - port: 9000
    protocol: TCP
    name: "9000"
    targetPort: 9000
  - port: 12201
    protocol: UDP
    name: "12201"
    targetPort: 12201
  selector:
    app: graylog
