apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor
  namespace: default
spec:
  rules:
  - host: monitor.app.lpscogna.site
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: monitor
              port:
                number: 8000
